### ISSUE TITLE
Error: CSS parse error js/main.js: Unexpected input

### ISSUE THREAD

**Issue by webjey** [endel/generator-modern-frontend#13]
Got this error after running:
$ gulp

=============================

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: CSS parse error js/main.js: Unexpected input
    1 |!function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var s=n[i]={exports:{}};e[i][0].call(s.exports,function(r){var n=e[i][1][r];return o(n?n:r)},s,s.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}({1:[function(r,e,n){"use strict";console.log("yay")},{}]},{},[1]);
-------^

==============================

**Comment by endel** [comment]
Hey @webjey.

I don't plan to maintain this project anymore. I'd highly recommend you to use webpack instead.

Cheers!
