### ISSUE TITLE
Handlebars integration

### ISSUE THREAD

**Issue by ebowers** [endel/generator-modern-frontend#4]
Hi there,

I'm curious how I could integrate handlebars into this build. I'm new to gulp/browserify.

Thanks!

**Comment by endel** [comment]
@ebowers do you mean compiling the `index.html` via handlebars, or being able to compile `.hbs` inside JavaScript?

For the first option, it can be done with [gulp-compile-handlebars](https://github.com/kaanon/gulp-compile-handlebars). 

I prefer the second one, using a browserify transform to precompile your handlebars templates directly via `require` function: https://github.com/dlmanning/browserify-handlebars

**Usage example:**

``` javascript
var template = require('./my_template.handlebars');
document.querySelector('#container').innerHTML = template()
```

Hope that helps. Please let me know if you have any doubt.

**Comment by ebowers** [comment]
@endel Thanks for the quick reply!

I think I would like to try out the browserify transform. A couple more questions to clarify...

In my gulp file, I tried adding it to the transforms already happening, but am not sure where to put the entrypoint.js file which I assume means the main.js file I require all of my modules in?

#### Gulpfile (the javascript task):

I tried using the .transform() pattern like you did with babelify and envify, but can really figure out where/how to list out the entry-point.js which I assume is the main.js file.

```
gulp.task('javascript', function () {
  return gulp.src('app/js/main.js')
    .pipe(through2.obj(function (file, enc, next){ // workaround for https://github.com/babel/babelify/issues/46
      browserify(file.path)
      .transform('babelify')
      .transform('envify')
      .transform('browserify-handlebars') // ???
      // browserify -t browserify-handlebars entry-point.js (not sure how to format this with transform)
      .bundle(function(err, res){
        if (err) { return next(err); }

        file.contents = res;
        next(null, file);
      });
    }))
    .on('error', function (error) {
      console.log(error.stack);
      this.emit('end');
    })
    .pipe(gulp.dest('dist/js'))
    .pipe($.sourcemaps.init())
    // .pipe($.uglify())
    .pipe($.sourcemaps.write('.'))
    .pipe(gulp.dest('.tmp/js'));
});
```

#### main.js

In my main.js file I required the template and passed it data, eventually I ran into an issue saying that the html variable is defined but not used. Sorry, I am still new to browserify.

```
var firstTemplate = require('./templates/first.handlebars');
var html = firstTemplate({title: "An instantiated template!", name: "David"});
```

Any idea how I can get this to compile correctly?

Thanks so much for your help!
- Evan

**Comment by endel** [comment]
Hey @ebowers, you've configured perfectly. 

The notices you're receiving isn't from browserify. It is coming from [jshint](https://github.com/endel/generator-modern-frontend/blob/3d1d9af5b1950e03726302160e243844b04b5a6b/app/templates/gulpfile.js#L91-L97) task, which is a tool to check your code consistency with best practices. You may disable it by removing from [build task](https://github.com/endel/generator-modern-frontend/blob/3d1d9af5b1950e03726302160e243844b04b5a6b/app/templates/gulpfile.js#L197).

Please let me know if you find any problem.
