### ISSUE TITLE
javascript being concatenated twice

### ISSUE THREAD

**Issue by mcfiredrill** [endel/generator-modern-frontend#6]
I always seem to end up with two copies of my Javascript concatenated together in my dist/main.js file. Then I remove the .tmp directory and it seems to fix the issue.

I guess technically I'm supposed to use `gulp clean` and it will remove that directory, but is it feasible to  remove the .tmp directory before the build starts if it exists, to help save users from this potential problem?

**Comment by endel** [comment]
Hey @mcfiredrill, 

Can you provide an example of the source and result of your `.js` files?
I've tested with the last version (0.1.7) and I didn't noticed the behavior you mentioned.

Thanks
