### ISSUE TITLE
[sass] Include sprites

### ISSUE THREAD

**Issue by Epenance** [endel/generator-modern-frontend#7]
Hi there,

I would like a quick guide on how to use the sprites in this setup, I've used this on a project as a test and i cant seem to figure out how to use/generate the sprites.

**Comment by endel** [comment]
Hi @Epenance,

Basically you'll need to create a directory per sprite category on `app/images/sprites`. Each sprite category will generate its respective stylesheet and sprite sheet.

Examples:
- `app/images/sprites/general/*.png` generates:
  - `css/sprites/general.styl`
  - `images/sprites_general.png`
- `app/images/sprites/heavy_stuff/*.png` generates:
  - `css/sprites/heavy_stuff.styl`
  - `images/sprites_heavy_stuff.png`

Thanks for reporting!

**Comment by Epenance** [comment]
@endel Thanks for the quick respond!

Unforturnately i seem to be getting an error when doing that.

You can see my error here: http://puu.sh/k5FJ3/65ad3b34f6.png

**Comment by endel** [comment]
Hi @Epenance,

That's unusual. Could you please paste your gulpfile.js in a [gist](http://gist.github.com)? 

The error message says that there is a function call on line 44 on something that doesn't exists. Maybe there is a dependency missing or something.

**Comment by Epenance** [comment]
@endel Here you go: https://gist.github.com/Epenance/6b6f39b443c03fe166d5

**Comment by Epenance** [comment]
@endel Okay, so it turns out that the package.json didnt have the gulp.spritesmith included, i added that and then the .scss file was generated, however the image was not. No errors this time around though.

**Comment by Epenance** [comment]
Okay, so i found the problem. The package gulp.spritesmith was not included in the package.json

Additionally i found out that i had to change the cssFormat in the gulpfile to scss rather than sass or it would leave out the semicolons at the end of each line.

**Comment by endel** [comment]
@Epenance oops, actually the generator is [not including this dependency for sass](https://github.com/endel/generator-modern-frontend/blob/92beb213b7e09a89cf542e03c50db26a105bf0fd/app/templates/_package.json#L30-L32), but it should. 

I didn't noticed that node-sass isn't capable of generating sprites.

This generator was tested mainly with stylus, [importing all the generated sprite stylesheets automatically](https://github.com/endel/generator-modern-frontend/blob/92beb213b7e09a89cf542e03c50db26a105bf0fd/app/templates/gulpfile.js#L25). Probably it will be needed to do the same thing [with sass](https://github.com/endel/generator-modern-frontend/blob/92beb213b7e09a89cf542e03c50db26a105bf0fd/app/templates/gulpfile.js#L21).

Please let me know if you find any problems, and also if you want to share your sass setup I'll be happy to merge it here.

**Comment by endel** [comment]
@Epenance as my search there is no way to include other sprite sheets automatically using [node-sass](https://github.com/sass/node-sass). :(

You'll need to import each of the sprite categories manually when you need to use it, unfortunately. But this isn't that bad actually.

I'm closing here, but please feel free to reopen if you find any trouble! 
Thank you
